let data=[
    {
        STT: "1",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "2",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "3",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "4",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "5",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "6",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "7",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "8",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "9",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "10",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "11",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "12",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "13",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "14",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "15",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "16",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "17",
        Date: "10/5/2000",
        PropertyCode: "TS00002",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "18",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "19",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "20",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "21",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "22",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      {
        STT: "23",
        Date: "10/5/2000",
        PropertyCode: "TS00001",
        PropertyName: "Xe ô tô HONDA CIVIC",
        PropertyType: "Ô tô",
        Department: "Phòng hành chính tổng hợp",
        Price: "754900000",
      },
      
]

export default data